version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_DATABASE=ManagerDb
      - MONGO_INITDB_USERNAME=teste
      - MONGO_INITDB_PASSWORD=teste@123
    volumes:
      - /Users/vinicius.oliveira/projetos/database/mongo:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped